using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Entities.GameManagement;
using Entities.Utils;
using JetBrains.Annotations;
using UnityEngine;

namespace Entities.WordProcessing
{
    public class WordProcessingManager : MonoBehaviour, IService
    {
        private class WordDataEntry
        {
            public string MainWord { get; set; }
            public float RecordedAoA { get; set; }
            public List<string> RelatedWords { get; set; }
            public int RatedTimes { get; set; }

            [UsedImplicitly]
            public bool Equals(WordDataEntry x, WordDataEntry y) => x.MainWord == y.MainWord;
            
            public WordDataEntry(string mainWord, float recordedAoA, List<string> relatedWords, int ratedTimes = 0)
            {
                MainWord = mainWord;
                RecordedAoA = recordedAoA;
                RelatedWords = relatedWords;
                RatedTimes = ratedTimes;
            }

            public void IncrementRatedTimes()
            {
                SetRatedTimes(RatedTimes + 5);
            }

            public void SetRatedTimes(int ratedTimes)
            {
                RatedTimes = ratedTimes;
                PlayerPrefs.SetInt(MainWord + "RatedTimes", RatedTimes);
                PlayerPrefs.Save();
            }
        }
        
        [SerializeField]
        private string _WordDataFilePath = "Assets/Entities/DataManagement/WordData.csv";
        
        [SerializeField]
        private char _MainSeparator = ';';
        
        [SerializeField]
        private char _RelatedWordsSeparator = ',';
        
        private List<WordDataEntry> _relatedWordData = new List<WordDataEntry>();
        
        private List<string> _unparsedRelatedWords = new List<string>()
        {
            "sekera;5.33;drevo,strom",
            "sud;4.76;barel,nádoba",
            "baterka;4.61;elektrina",
            "opasok;4.15;nohavice,gate",
            "tabuľa;5.18;krieda,fixka",
            "kosť;4.45;telo,rebro,lebka",
            "reťaz;4.56;železo,zámok",
            "počítač;7.88;monitor,klávesnica,internet",
            "krokodíl;4.61;aligátor",
            "písací stôl;4.78;kancelária,pero",
            "obálka;4.91;list,pošta",
            "pierko;4.24;vták,krídlo",
            "vlajka;5.85;symbol,štát",
            "panvica;4.00;varenie,sporák",  
            "gitara;4.55;hudba,struny",
            "revolver;5.67;zbraň,pištol",
            "vrtuľník;5.06;helikoptéra,lietadlo",
            "žehlička;4.18;oblečenie,teplo",
            "klokan;4.91;austrália,vak",
            "rebrík;4.06;schody,liezť",
            "zapalovač;6.12;oheň,cigareta",
            "rúž;4.61;pery,ústa",
            "zápalka;4.24;oheň",
            "huba;4.36;hríb,les",
            "ihla;4.00;šitie,niť",
            "hniezdo;3.91;osa,včela",
            "noviny;4.00;správy,papier",
            "štetec;4.03;obraz,maľba",
            "tučniak;5.09;vták,ľad",
            "ananás;4,78;ovocie",
            "pizza;7.91;jedlo",
            "poštár;4.21;práca,list",
            "raketa;5.42;vesmír,mesiac,letieť",
            "strecha;3.85;dom,škridle",
            "pravítko;5.39;centimeter,merať",
            "obložený chlebíček;4.82;jedlo",
            "píla;5.09;rezať,drevo",
            "váha;4.64;kilo,závažie",
            "šijací stroj;4.39;oblečenie,ihľa",
            "slnečné okuliare;4.70;tvár,oči,slnko",
            "tank;5.31;vojna,brnenie",
            "tenisová lopta;6.09;hra,raketa",
            "teplomer;4.00;choroba,horúčka",
            "kravata;5.48;oblek,krk",
            "tiger;4.00;mačka,šelma,pásiky",
            "kamión;4.91;doprava",
            "korytnačka;4.25;zviera,pancier",
            "vlna;4.67;ovca",
            "zebra;4.27;zviera,afrika",
            "žobrať;6.00;prosiť",
            "vrieť;4.88;horúce,variť",
            "boxovať;5.70;súboj,bitka",
            "prasknúť;4.09;bublina",
            "vyrezávať;5.67;drevo,nôž",
            "dirigovať;5.22;koncert,hudba,orchester",
            "rýlovať;4.39;záhrada,farma",
            "vŕtať;4.85;diera",
            "šoférovať;4.27;auto,volant",
            "topiť sa;4.73;more,voda,smrť",
            "vybuchnúť;5.36;bomba,dynamit",
            "hasiť;4.58;oheň,požiar,voda",
            "pilovať;6.89;zlepšovať,trénovať",
            "pražiť;5.52;olej,panvica",
            "strúhať;4.27;jablko,mrkva",
            "grilovať;6.58;mäso,uhlie",
            "liahnuť;5.21;vajce",
            "stopovať;6.24;cestovať,auto",
            "loviť;5.18;zver,puška,chytať",
            "štrikovať;4.67;ihly,šál,sveter",
            "zapalovať;4.42;oheň,drevo",
            "vydávať sa;5.36;svadba,manželstvo",
            "masírovať;6.03;svaly,relax",
            "merať;4.58;vzdialenosť,váha",
            "dojiť;5.15;mlieko,krava",
            "šľahať;4.82;smotana",
            "zmývať;4.81;čistiť",
            "operovať;5.91;liečiť",
            "lúpať;4.36;orech",
            "fotografovať;4.45;kamera",
            "sadiť;4.15;rastliny,farma,záhrada",
            "orať;4.70;farma,úroda",
            "hrabať;4.00;hlina,lopata",
            "jazdiť;4.12;kôň,motorka",
            "opekať;4.61;oheň,špekačky",
            "veslovať;6.21;čln,kajak",
            "plaviť sa;5.52;loď,more",
            "píliť;4.55;drevo,strom",
            "šiť;3.85;ihľa,oblečenie,látka",
            "brúsiť;5.64;naostriť,nôž,čepel",
            "holiť sa;5.03;brada,fúzy",
            "korčuľovať;4.97;ľad,hokej",
            "lyžovať sa;4.79;sneh",
            "fajčiť;4.79;cigareta,tabak",
            "priasť;6.24;niť",
            "žmýkať;4.76;sušiť,prať",
            "kradnúť;4.88;brať,zločin",
            "opalovať sa;4.82;slnko,pláž",
            "surfovať;7.22;vlny,more",
            "potiť sa;5.33;cvičiť",
            "vážiť;4.27;kilogram"
        };


        private List<string> _unrelatedWords = new List<string>()
        {
            "vajce",
            "cylinder",
            "sezónny",
            "nesúhlas",
            "schodisko",
            "jednoducho",
            "bariéra",
            "pozdrav",
            "hadica",
            "omdlievať",
            "klásť",
            "zviera",
            "novina",
            "balík",
            "krútiť",
            "mačka",
            "rasa",
            "napumpovať",
            "vytvoriť",
            "cieva",
            "omladenie",
            "poriadny",
            "odvolať",
            "morský",
            "ohrada",
            "opora",
            "žltá",
            "naraz",
            "budúci",
            "preberať",
            "hlasno",
            "pálka",
            "duet",
            "zápisník",
            "farba",
            "dolár",
            "severský",
            "mladík",
            "rovnako",
            "rozvinutý",
            "nepriamy",
            "prejav",
            "agentúra",
            "štatistika",
            "peniaze",
            "škorpión",
            "ikona",
            "hrdina",
            "pomocný",
            "odklad",
            "komisia",
            "pomer",
            "hľadanie",
            "umenie",
            "poslucháč",
            "citlivý",
            "kniha",
            "kryt",
            "člen",
            "priaznivo",
            "naopak",
            "skaza",
            "rýchly",
            "juhozápad",
            "číslo",
            "drsný",
            "nárek",
            "doľava",
            "nádrž",
            "hlasovať",
            "ozajstný",
            "podnet",
            "pohyb",
            "bahnisko",
            "pokúšanie",
            "nepríjemne",
            "internet",
            "noha",
            "petičný",
            "návrat",
            "pokojne",
            "bezpečie",
            "hravosť",
            "duševný",
            "dynamika",
            "hojdať",
            "hlúpy",
            "nepriateľ",
            "hĺbka",
            "oslávenec",
            "dráždiť",
            "dekorovať",
            "poslúžiť",
            "kabát",
            "jazdec",
            "výboj",
            "ohnisko",
            "bylina",
            "hanba",
            "dávka",
            "farský",
            "odborný",
            "odchýlka",
            "prepustený",
            "pracujúci",
            "šepot",
            "primeraný",
            "obrovský",
            "iste",
            "zažiariť",
            "dreň",
            "odovzdanie",
            "odpisovať",
            "natiahnuť",
            "nepresný",
            "aristokrat",
            "motorika",
            "slza",
            "krst",
            "baba",
            "druh",
            "obliecť",
            "brať",
            "digitálny",
            "pôvabný",
            "podtrhnúť",
            "ruch",
            "použitie",
            "meniť",
            "chápanie",
            "meštiacky",
            "celtovina",
            "prasknutie",
            "hnusný",
            "smutný",
            "otrok",
            "fľaša",
            "objednať",
            "logicky",
            "osobnosť",
            "zrážky",
            "parník",
            "deflektor",
            "rovnakosť",
            "aktívny",
            "maštaľ",
            "kopa",
            "vedome",
            "mláďa",
            "líšiť",
            "okno",
            "krach",
            "bodovať",
            "družstvo",
            "ústie",
            "demokracia",
            "naplnený",
            "prisľúbiť",
            "náuka",
            "konflikt",
            "veža",
            "svet",
            "október",
            "golf",
            "miesto",
            "jedinečný",
            "kvartál",
            "dohady",
            "atraktívny",
            "nanajvýš",
            "poznanie",
            "prírastok",
            "duplikát",
            "breh",
            "cudný",
            "planéta",
            "odkladať",
            "kôrovec",
            "zmenšenie",
            "ubytovať",
            "následne",
            "horenie",
            "brod",
            "potešenie",
            "dotyk",
            "minimálny",
            "konanie",
            "skok",
            "obmedzenie",
            "hliníkový",
            "veľkosť",
            "agresia",
            "nemecký",
            "bojovný",
            "akútny",
            "mustang",
            "inflácia",
            "potraviny",
            "prítomný",
            "bočnica",
            "blahoželať",
            "metóda",
            "zármutok",
            "barokový",
            "doska",
            "cifra",
            "škridla",
            "anglický",
            "kotlisko",
            "pochybenie",
            "hryzač",
            "banka",
            "neistý",
            "súvisieť",
            "pomaly",
            "priemysel",
            "hygienik",
            "hlasný",
            "pozostalý",
            "vydržať",
            "uhol",
            "oddaný",
            "fonológia",
            "kvazar",
            "silne",
            "medovina",
            "zrada",
            "brzdenie",
            "hnev",
            "slávnosť",
            "nabádať",
            "pripevniť",
            "parcela",
            "prekvitať",
            "absolútny",
            "upokojiť",
            "oslabený",
            "klam",
            "odstaviť",
            "lacno",
            "driemať",
            "kontext",
            "idol",
            "plánovaný",
            "pridať",
            "kancelária",
            "stehno",
            "premena",
            "profesia",
            "ústa",
            "kresliar",
            "spokojnosť",
            "motivačný",
            "interiér",
            "editor",
            "vyšívanie",
            "náhrada",
            "srbský",
            "fragment",
            "pracovníci",
            "výbor",
            "pokročiť",
            "gigantický",
            "dokázať",
            "embargo",
            "tymín",
            "pevnina",
            "odpor",
            "cestovný",
            "kšeftár",
            "oblastný",
            "nachodiť",
            "mrzieť",
            "prebudiť",
            "optimista",
            "nahý",
            "bielizeň",
            "chvatne",
            "potrvať",
            "bludár",
            "celkom",
            "bieda",
            "družstevný",
            "podšívka",
            "trombóza",
            "placenta",
            "nebezpečný",
            "podceniť",
            "obrad",
            "priradiť",
            "obmedziť",
            "krik",
            "ľadovec",
            "požehnanie",
            "dejisko",
            "kaziť",
            "dôstojník",
            "očko",
            "pohnúť",
            "naplnenie",
            "klesať",
            "chrbát",
            "tolerancia",
            "stráň",
            "konečne",
            "cvoknutý",
            "natierač",
            "panský",
            "nosný",
            "hurikán",
            "rozširovať",
            "bezcitnosť",
            "dobročinný",
            "krutosť",
            "útlak",
            "obrnený",
            "ohnivý",
            "nemravný",
            "okamžite",
            "ples",
            "podliak",
            "cyklus",
            "priľahlý",
            "vedomosti",
            "hovorový",
            "dominovať",
            "vysielač",
            "sieť",
            "dvor",
            "bujarý",
            "vážny",
            "posilniť",
            "bezradný",
            "starý",
            "vytrvalo",
            "brvno",
            "kríza",
            "bolieť",
            "pečivo",
            "doporučiť",
            "šerbet",
            "estetický",
            "obľúbený",
            "banalita",
            "dôvera",
            "preddavok",
            "rovný",
            "krajčír",
            "nevýhoda",
            "maximálny",
            "kopyto",
            "chrumkavý",
            "móda",
            "áron",
            "hrubý",
            "prístup",
            "ateliér",
            "pravda",
            "ženáč",
            "oštep",
            "písmeno",
            "prieskum",
            "odrážať",
            "ostať",
            "akcie",
            "dospelý",
            "informácia",
            "hutný",
            "stratiť",
            "preliať",
            "hostiť",
            "severný",
            "nariadiť",
            "bičovať",
            "povzbudiť",
            "opatrnosť",
            "kuriér",
            "klient",
            "investor",
            "strom",
            "fyzicky",
            "podoba",
            "klíma",
            "klad",
            "majetok",
            "knižnica",
            "hmotný",
            "zápas",
            "dosah",
            "milosť",
            "detail",
            "chrám",
            "žobrák",
            "usmerňovač",
            "nealko",
            "náležitý",
            "pamiatka",
            "pretrpieť",
            "celý",
            "chvíľa",
            "plátanie",
            "kričať",
            "hostinec",
            "oddanosť",
            "medzera",
            "mystický",
            "fungovať",
            "nadšenie",
            "kontrola",
            "nadanie",
            "dole",
            "jadro",
            "reflektor",
            "koreň",
            "mladosť",
            "plátno",
            "revolučný",
            "petrolej",
            "vzdychať",
            "nočný",
            "bandita",
            "fungujúci",
            "prakticky",
            "zisk",
            "kalich",
            "odolnosť",
            "neporiadok",
            "oranžový",
            "inštrukcia",
            "ohradenie",
            "korčuľa",
            "miera",
            "odlákať",
            "dáta",
            "objaviť",
            "dlžný",
            "výstuž",
            "merateľný",
            "nepokoj",
            "uzáver",
            "pozadie",
            "lôžko",
            "inštitúcia",
            "prameniť",
            "porušený",
            "hrdlo",
            "obnova",
            "cvičiť",
            "obradný",
            "prerušenie",
            "drôt",
            "narukovať",
            "bohatstvo",
            "nesúhlasiť",
            "posvätný",
            "jedovatý",
            "obdarený",
            "záchranca",
            "tlmič",
            "nahnevane",
            "pašerák",
            "nepoznaný",
            "špic",
            "plodina",
            "divák",
            "politik",
            "podvečer",
            "otvorenosť",
            "pohár",
            "chod",
            "neskorý",
            "farbenie",
            "pokračovať",
            "namietať",
            "oblečenie",
            "rozvodniť",
            "história",
            "ľadvina",
            "opustený",
            "absurdný",
            "pilne",
            "jedlo",
            "dialóg",
            "obdarovaný",
            "nápadne",
            "nulový",
            "napadnúť",
            "pracka",
            "ovládnutý",
            "nevyhnutný",
            "padať",
            "humor",
            "hrozný",
            "neistota",
            "požičať",
            "objavenie",
            "klamstvo",
            "fontána",
            "stredovek",
            "teleso"
        };
        
        public void Start()
        {
            GameManager.AddService(this);

            foreach (var line in _unparsedRelatedWords)
            {
                var result = CsvReader.ParseLine(line, _MainSeparator);
                var aoa = float.Parse(result[1], CultureInfo.InvariantCulture.NumberFormat);
                var relatedWords = result[2].Split(_RelatedWordsSeparator).ToList();
                var ratedTimes= PlayerPrefs.GetInt(result[0] + "RatedTimes", 0);
                
                _relatedWordData.Add(new WordDataEntry(result[0], aoa, relatedWords, ratedTimes));
            }      
        }

        public WordTriple GetWordTriple()
        {
            var maxRatedTimes = _relatedWordData.Max(r => r.RatedTimes);
            var mainWordData = RandomUtils.WeightedRandomFromList(_relatedWordData, i => Mathf.Max(maxRatedTimes - i.RatedTimes, 1));
            var incorrectWord = RandomUtils.RandomFromList(_unrelatedWords);
            return new WordTriple
            (
                mainWordData.MainWord, 
                RandomUtils.RandomFromList(mainWordData.RelatedWords), 
                incorrectWord,
                mainWordData.RecordedAoA
            );
        }

        public string NicifyWord(string word)
        {
            var newWord = word.Replace("_", " ");
            return char.ToUpper(newWord[0]) + newWord[1..];
        }
        

        public void IncrementRatedTimes(string mainWord)
        {
            var mainWordData = _relatedWordData.Find(r => r.MainWord == mainWord);
            mainWordData.IncrementRatedTimes();

            var floor = _relatedWordData.Min(r => r.RatedTimes);
            if (floor > 0)
            {
                foreach (var item in _relatedWordData)
                {
                    item.SetRatedTimes(item.RatedTimes - floor);
                }
            }
        }
    }
}